controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    ack_cont:
      type: ackermann_steering_controller/AckermannSteeringController
    

    
    
ack_cont:
  ros__parameters:
    front_steering: true
    open_loop: false
    velocity_rolling_window_size: 10
    position_feedback: false
    use_stamped_vel: true
    rear_wheels_names: [back_right_wheel_joint, back_left_wheel_joint]
    front_wheels_names: [front_right_wheel_joint, front_left_wheel_joint]
    front_wheel_track: 0.05
    rear_wheel_track: 0.05
    front_wheels_radius: 0.1
    rear_wheels_radius: 0.1

 
