controller_manager:
  ros__parameters:
    update_rate: 30 # Hz
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


diff_cont:
  ros__parameters:
    left_wheel_names: ['front_left_wheel_joint', 'back_left_wheel_joint']
    right_wheel_names: ['front_right_wheel_joint','back_right_wheel_joint']
    wheel_radius: 0.1
    wheel_separation: 0.3
    publish_rate: 50.0 # defaults to 50
    cmd_vel_timeout: 20.0 # we test this separately, give plenty for the other tests
    use_stamped_vel: false


