controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster



velocity_controller:
  ros__parameters:
    joints:
      - back_left_wheel_joint
      - back_right_wheel_joint
      - front_left_wheel_joint
      - front_right_wheel_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity

 
